//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PictureGallery {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PictureGallery.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Picture Gallery app is a flickr browser that allows users to explore and search the flickr photo and author databases. Users can pin favorite photos, authors, galleries and search results..
        /// </summary>
        public static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send feedback.
        /// </summary>
        public static string AboutSendFeedback {
            get {
                return ResourceManager.GetString("AboutSendFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comments.
        /// </summary>
        public static string CommentPlural {
            get {
                return ResourceManager.GetString("CommentPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to curated.
        /// </summary>
        public static string Curated {
            get {
                return ResourceManager.GetString("Curated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorites.
        /// </summary>
        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gallery.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to galleries.
        /// </summary>
        public static string GalleryPlural {
            get {
                return ResourceManager.GetString("GalleryPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hot for today.
        /// </summary>
        public static string HotForToday {
            get {
                return ResourceManager.GetString("HotForToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last 7 days.
        /// </summary>
        public static string Last7Days {
            get {
                return ResourceManager.GetString("Last7Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add favorites by tapping on the pin to fav button on user, tag, gallery or photo page.
        /// </summary>
        public static string NoFavorites {
            get {
                return ResourceManager.GetString("NoFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure airplane mode is turned off and you still have a cellular data or Wi-Fi connection..
        /// </summary>
        public static string NoNetwork {
            get {
                return ResourceManager.GetString("NoNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network unavailable.
        /// </summary>
        public static string NoNetworkTitle {
            get {
                return ResourceManager.GetString("NoNetworkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving information is disabled. Your favorites will not be saved when the application exits..
        /// </summary>
        public static string PersistenceDisabled {
            get {
                return ResourceManager.GetString("PersistenceDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photo.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photos.
        /// </summary>
        public static string PhotoPlural {
            get {
                return ResourceManager.GetString("PhotoPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin to fav.
        /// </summary>
        public static string Pin {
            get {
                return ResourceManager.GetString("Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prev.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reload.
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no photos were found.
        /// </summary>
        public static string SearchNoPhotos {
            get {
                return ResourceManager.GetString("SearchNoPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to people.
        /// </summary>
        public static string SearchPeople {
            get {
                return ResourceManager.GetString("SearchPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search for username, email, photo.
        /// </summary>
        public static string SearchTextBoxWatermark {
            get {
                return ResourceManager.GetString("SearchTextBoxWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unpin.
        /// </summary>
        public static string Unpin {
            get {
                return ResourceManager.GetString("Unpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there are no uploaded galleries.
        /// </summary>
        public static string UserNoGalleries {
            get {
                return ResourceManager.GetString("UserNoGalleries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there are no uploaded photos.
        /// </summary>
        public static string UserNoPhotos {
            get {
                return ResourceManager.GetString("UserNoPhotos", resourceCulture);
            }
        }
    }
}
